# Generated by Django 3.1.3 on 2020-11-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo UABC')),
                ('status', models.CharField(blank=True, choices=[(None, 'Selecciona estado'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25, verbose_name='Estado')),
                ('rol', models.CharField(choices=[(None, 'Seleccionar rol'), ('Profesor/Investigador', 'Profesor/Investigador'), ('Tecnico academico', 'Tecnico academico'), ('Estudiante licenciatura', 'Estudiante licenciatura'), ('Estudiante postgrado', 'Estudiante postgrado')], max_length=25, verbose_name='Rol en UABC')),
                ('is_staff', models.BooleanField(default=False, help_text='IMPORTANTE. Marcar esta casilla le da al usuario acceso completo a  este sitio de administracion.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('image', models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_images', verbose_name='Imagen del perfil')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account', verbose_name='Informacion personal')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
            },
        ),
    ]
