# Generated by Django 3.1.3 on 2020-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersap',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
