# Generated by Django 3.1.3 on 2020-11-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_author_info'),
        ('userSap', '0002_auto_20201127_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersap',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Informacion personal'),
        ),
    ]
