# Generated by Django 3.1.3 on 2020-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeP', models.CharField(choices=[(None, 'Selecciona estado'), ('Interno', 'Interno'), ('Externo', 'Externo'), ('Convenio', 'Convenio'), ('UABC', 'UABC')], max_length=25, verbose_name=' Tipo de proyecto')),
                ('title', models.CharField(max_length=100, verbose_name='Título de proyecto')),
                ('announcement', models.CharField(blank=True, max_length=100, verbose_name=' Convocatoria (Si aplica)')),
                ('amount', models.CharField(blank=True, max_length=50, verbose_name='Presupuesto (Si aplica)')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Clave')),
                ('vigent', models.DateField(blank=True, verbose_name='Vigencia hasta')),
                ('status', models.CharField(blank=True, choices=[(None, 'Selecciona estado'), ('Vigente', 'Vigente'), ('No vigente', 'No vigente'), ('Concluido', 'Concluido')], max_length=25, verbose_name='Estado del proyecto')),
                ('createdPubProject', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, to='account.Account', verbose_name='Participantes')),
            ],
        ),
    ]
