# Generated by Django 3.1.3 on 2020-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201125_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto'},
        ),
    ]
