# Generated by Django 3.1.3 on 2021-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201211_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Presupuesto (Si aplica)'),
        ),
    ]
