# Generated by Django 3.1.3 on 2020-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookChapter', '0003_bookchapter_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'verbose_name': 'Capitulo'},
        ),
    ]
