# Generated by Django 3.1.3 on 2020-12-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201128_1328'),
        ('event', '0002_auto_20201128_1328'),
        ('bookChapter', '0004_auto_20201128_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='academyTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.academy', verbose_name='Cuerpo académico educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='bookIsbn',
            field=models.CharField(max_length=100, verbose_name='ISBN del libro'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='eventPublication',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event', verbose_name='Evento en el que fue publicado'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(upload_to='archiving/', verbose_name='Capitulo de libro (PDF)'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='programTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.program', verbose_name='Programa educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del capitulo'),
        ),
    ]
