# Generated by Django 3.1.3 on 2021-01-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookChapter', '0005_auto_20201211_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='file',
            field=models.FileField(unique=True, upload_to='archiving/', verbose_name='Capitulo de libro (PDF)'),
        ),
    ]
