# Generated by Django 3.1.3 on 2020-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Articulo'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Revista'},
        ),
    ]
