# Generated by Django 3.1.3 on 2020-12-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201211_0647'),
        ('account', '0004_auto_20201128_1328'),
        ('event', '0002_auto_20201128_1328'),
        ('article', '0004_auto_20201128_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='academyTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.academy', verbose_name='Cuerpo académico educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='arbitration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Arbitraje'),
        ),
        migrations.AlterField(
            model_name='article',
            name='eventPublication',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event', verbose_name='Evento en el que fue publicado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='archiving/', verbose_name='Articulo (PDF)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='indexInfo',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Índice en que se encuentra'),
        ),
        migrations.AlterField(
            model_name='article',
            name='indexed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Indizado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.journal', verbose_name='Nombre de revista'),
        ),
        migrations.AlterField(
            model_name='article',
            name='programTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.program', verbose_name='Programa educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[(None, 'Selecciona estado'), ('En proceso', 'En proceso'), ('Sometido', 'Sometido'), ('Liberado', 'Liberado')], default='Sometido', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=220, unique=True, verbose_name='Título de artículo'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(max_length=30, unique=True, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la revista'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='quartMagazine',
            field=models.CharField(choices=[(None, 'Selecciona cuartiles'), (' q1 ', ' q1 '), (' q2 ', ' q2 '), (' q3 ', ' q3 '), (' q4 ', ' q4 ')], max_length=25, verbose_name='Cuartiles'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='referenceMagazine',
            field=models.CharField(blank=True, max_length=100, verbose_name='Enlace a revista'),
        ),
    ]
