# Generated by Django 3.1.3 on 2020-12-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201212_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='year',
            new_name='publicationYear',
        ),
    ]
