# Generated by Django 3.1.3 on 2021-01-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20201212_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(unique=True, upload_to='archiving/', verbose_name='Articulo (PDF)'),
        ),
    ]
