# Generated by Django 3.1.3 on 2020-11-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201125_1337'),
        ('account', '0001_initial'),
        ('event', '0001_initial'),
        ('book', '0003_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='academyTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.academy', verbose_name='Cuerpo académico educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='eventPublication',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event', verbose_name='Evento en el que fue publicado'),
        ),
        migrations.AlterField(
            model_name='book',
            name='programTribute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='account.program', verbose_name='Programa educativo al que tributa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='Proyecto'),
        ),
    ]
