# Generated by Django 3.1.3 on 2020-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201125_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='timeStamp',
            field=models.DateField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
