# Generated by Django 3.1.3 on 2020-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201125_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
