# Generated by Django 3.1.3 on 2020-11-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Cuerpo académico')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del programa')),
                ('key', models.CharField(blank=True, max_length=150, verbose_name='Clave del programa')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEmp', models.CharField(blank=True, max_length=20, verbose_name='Numero de empleado')),
                ('firstName', models.CharField(blank=True, max_length=50, verbose_name='Nombre(s)')),
                ('lastNameA', models.CharField(blank=True, max_length=50, verbose_name='Apellido Paterno')),
                ('lastNameB', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.academy', verbose_name='Cuerpo académico')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.program', verbose_name='Programa educativo')),
            ],
        ),
    ]
