# Generated by Django 3.1.3 on 2020-11-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='author_info',
            field=models.ForeignKey(default=555, on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Define esta cuenta con un registro en la tabla de autores'),
            preserve_default=False,
        ),
    ]
