# Generated by Django 3.1.3 on 2020-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Congreso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('eventCreated', models.CharField(blank=True, max_length=100, verbose_name='Fecha de creacion del evento')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Tema')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='Sede')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del evento')),
                ('eventCreated', models.CharField(blank=True, max_length=100, verbose_name='Fecha de creacion del evento')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Tema')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='Sede')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('event', models.CharField(blank=True, choices=[(None, 'Seleccionar tipo'), ('Congreso', 'Congreso'), ('Foro', 'Foro'), ('Simposio', 'Simposio')], max_length=100, verbose_name='Tipo')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Foro')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('eventCreated', models.CharField(blank=True, max_length=100, verbose_name='Fecha de creacion del evento')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Tema')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='Sede')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Symposium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del evento')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Tema')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('eventCreated', models.CharField(blank=True, max_length=100, verbose_name='Fecha de creacion del evento')),
                ('headquarters', models.CharField(blank=True, max_length=100, verbose_name='Sede')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
            ],
        ),
    ]
